image:
  file: .gitpod.Dockerfile

tasks:
  - name: Shopware
    before: |
      echo 'alias admin-watch="APP_URL=http://localhost:8000 composer run watch:admin"' >> ~/.bashrc
    init: |
      EXTENSION_NAME=$(basename $PWD)
      TMP_DIR=$(mktemp -d)
      
      mv * .* "$TMP_DIR" || true
      
      git clone https://github.com/shopware/platform --depth=1 .
      
      # Run MySQL
      docker run --restart always -d --name=mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8
      docker run --restart always -d --link mysql:mysql -p 5000:8080 -e ADMINER_DESIGN=pepa-linha -e ADMINER_DEFAULT_SERVER=mysql -e ADMINER_PLUGINS="tables-filter table-structure json-column version-noverify" ghcr.io/shyim/shopware-docker/adminer

      # Configure Shopware
      composer install
      ./bin/console system:setup -n --database-url "mysql://root:root@127.0.0.1:3306/shopware" --app-url "$(gp url 8000)" --app-env dev
      
      # Setup Trusted Proxies
      echo "TRUSTED_PROXIES=192.168.0.0/16" >> .env
      composer run setup
      
      # Move actual repository
      
      mkdir -p custom/plugins || true
      mv "$TMP_DIR" "custom/plugins/$EXTENSION_NAME"
    command: symfony serve --port=8000

ports:
  - port: 8000
    visibility: private
    description: Shopware
    onOpen: open-browser
  - port: 5000
    visibility: private
    description: Adminer
    onOpen: notify
  - name: Admin-Watcher
    port: 8080
    onOpen: notify
    description: "Use Forward Proxy to localhost to access this service"

jetbrains:
  plugins:
    - com.jetbrains.php
    - com.intellij.php.tools.quality.phpstan
    - com.intellij.php.psalm
    - org.jetbrains.plugins.yaml
    - com.jetbrains.twig
    - de.espend.idea.php.annotation
    - fr.adrienbrault.idea.symfony2plugin
    - de.shyim.shopware6
    - de.shyim.ideaphpstantoolbox

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
