services:
  shopware:
    image: dockware/dev:latest
    container_name: FroshTools
    ports:
      - "80"
      - "3306"
    volumes:
      - "./:/var/www/html/custom/plugins/FroshTools"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
networks:
  web:
    name: web
    driver: bridge
    external: true