name: PHP

on:
  pull_request:
    paths:
      - '**/*.php'
      - composer.json
      - phpunit.xml
      - .github/workflows/php.yml
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - composer.json
      - phpunit.xml
      - .github/workflows/php.yml
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware-version:
          - '6.6.x'
          - 'trunk'
        mysql-version:
          - 'builtin'
          - 'mariadb:11.8'
    steps:
      - name: Setup Extension
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          shopwareVersion: ${{ matrix.shopware-version }}
          mysqlVersion: ${{ matrix.mysql-version }}
          extraRepositories: |-
            {
              "local-plugins": {
                "type": "path",
                "url": "custom/plugins/*"
              }
            }

      - name: Run PHPUnit
        uses: shopware/github-actions/phpunit@main
        with:
          extensionName: ${{ github.event.repository.name }}
          uploadCoverage: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  opensearch:
    runs-on: ubuntu-latest
    services:
      opensearch:
        image: opensearchproject/opensearch:2
        env:
          discovery.type: single-node
          DISABLE_SECURITY_PLUGIN: 'true'
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'myWeakPassword123!'
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    env:
      OPENSEARCH_URL: http://localhost:9200
      SHOPWARE_ES_ENABLED: '1'
      SHOPWARE_ES_INDEXING_ENABLED: '1'
    steps:
      - name: Setup Extension
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          extraRepositories: |-
            {
              "local-plugins": {
                "type": "path",
                "url": "custom/plugins/*"
              }
            }

      - name: Run PHPUnit
        uses: shopware/github-actions/phpunit@main
        with:
          extensionName: ${{ github.event.repository.name }}
