name: Build extension
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Release Extension to Store
              uses: shopware/github-actions/store-release@main
              with:
                  extensionName: ${{ github.event.repository.name }}
                  clientId: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_ID }}
                  clientSecret: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET }}
                  ghToken: ${{ secrets.GITHUB_TOKEN }}
