name: Build extension
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        uses: shopware/github-actions/.github/workflows/store-release.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
        secrets:
            clientId: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_ID }}
            clientSecret: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
